### ISSUE TITLE
Not work on macos

### ISSUE THREAD

**Issue by zhigangjiang** [fuenwang/360LayoutVisualizer#1]
# environment
os: 
macOS Big Sure 11.2.2 

---
python 3.6

---
pip:
certifi==2016.2.28
cycler==0.10.0
imageio==2.9.0
kiwisolver==1.3.1
matplotlib==3.3.4
numpy==1.19.5
opencv-python==4.5.1.48
Pillow==8.2.0
PyGLM==2.1.1
PyOpenGL==3.1.5
pyparsing==2.4.7
PyQt5==5.15.4
PyQt5-Qt5==5.15.2
PyQt5-sip==12.8.1
python-dateutil==2.8.1
scipy==1.5.4
six==1.15.0

---
# result

<img width="1069" alt="Screen Shot 2021-05-03 at 3 58 32 PM" src="https://user-images.githubusercontent.com/29976583/116853312-6a7a4780-ac28-11eb-935b-3cbb5d96101d.png">

It's probably an OpenGL problem, although follow the tips [here](https://github.com/PixarAnimationStudios/USD/issues/1372#issuecomment-716925973)

**Comment by fuenwang** [comment]
Hi 

I also use BigSur to develop this repo. I have modified "OpenGL/platform/ctypesloader.py" as
![image](https://user-images.githubusercontent.com/13130716/116873461-4e879d80-ac4a-11eb-92ef-8671b04d755c.png)

and the repo should run without error.

**Comment by zhigangjiang** [comment]
Hi, thank reply.
I tried again and found it was not a white screen problem.  I moved the mouse, the results are as follows:
<img width="1509" alt="Screen Shot 2021-05-04 at 12 29 58 PM" src="https://user-images.githubusercontent.com/29976583/116960932-74f21b00-acd4-11eb-9981-859323bab538.png">

I use your example data and executed the command ```python visualizer.py --img src/example.jpg --json src/example.json```

Can you tell me your python and third-party library of pip versions?

**Comment by fuenwang** [comment]
Hi
After many times of trial and error, I found there might be bugs in PyGLM 2.1. Please downgrade the version.
```
pip install pyglm==1.99.0
```
The requirements.txt is also updated now.

**Comment by zhigangjiang** [comment]
thx, It's working.
:)
