### ISSUE TITLE
How to run it on the mode of off-screen-rendering

### ISSUE THREAD

**Issue by Gaowz112** [fuenwang/360LayoutVisualizer#2]
Hi，thanks for your excellent work！I wonder that is there any way to save the rendered image rather than displaying the image on the screen. I am not familiar with QT，can you give me some advice?

**Comment by fuenwang** [comment]
Currently, I didn't implement the screen saver. To implement this, you may need to use FrameBuffer in OpenGL to extract the rendered image and save it. I guess the difficulty will lie on OpenGL not Qt.

**Comment by Gaowz112** [comment]
Thanks，I'll try it. I have no further questions~
